spring.application.name=cos
server.port=8080
# ÌÚÑ¶COS
tencent.cos.file.region: ap-nanjing
tencent.cos.file.secretid: AKID5HZAqWDtVC2iQm9lIhZDdzBAzax86sQj
tencent.cos.file.secretkey: CSYEpGYgbJo6B16xazGNGvLWTBTaT7Wi
tencent.cos.file.bucketname: xcloud-1322447535
