spring.application.name=minio
server.port=8080
server.servlet.context-path=/api
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
server.minio.access-key=minioadmin
server.minio.secret-key=minioadmin
server.minio.endpoint=http://localhost:9000
server.minio.bucket=miniotest
knife4j.setting.language=zh-CN
knife4j.setting.enable=true